version: "3"
services:
  mongodb:
    image: ghcr.io/cookify-webapp/cookify-database
    container_name: "mongodb"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./init-script/init-script.js:/docker-entrypoint-initdb.d/init-script.js:ro
      - ./mongo-data:/data/db
networks:
    default:
      external:
        name: cookify-devops_cookify-webapp
